version: '3.8'

services:
  backend:
    build: .
    container_name: spotify-playlist-recommender_backend
    ports:
      - '8080:3000'
    env_file:
      - .env
      - .docker-env
    depends_on:
      - db
    networks:
      - recommender-network

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5436:5432'
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - recommender-network

volumes:
  db-data:
networks:
  recommender-network: