version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=secret
    restart: always
    ports:
      - '5436:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
