name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5436:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Determine Node version
        id: engines
        run: |
          echo "##[set-output name=NODE_VERSION;]$(jq -r '.engines.node' package.json)"
      - name: Set up Node.js ${{ steps.engines.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.engines.outputs.NODE_VERSION }}
      - name: Install packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run test:build
      - name: Test
        run: npm test