name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PORT: 3000
  POSTGRES_DB_HOST: localhost
  POSTGRES_DB_PORT: 5436
  POSTGRES_DB_ENTITIES: src/entity/*.entity.ts
  POSTGRES_DB_NAME: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret
  POSTGRES_SYNCHRONIZE: true
  POSTGRES_LOGGING: false

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5436:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine Node version
        id: engines
        run: |
          echo "##[set-output name=NODE_VERSION;]$(jq -r '.engines.node' package.json)"
      - name: Set up Node.js ${{ steps.engines.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.engines.outputs.NODE_VERSION }}
      - name: Build
        run: |
          npm ci
          npm run test:build
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm test